export const professionIcons = {
  'Blacksmithing': 'https://wow.zamimg.com/images/wow/icons/large/trade_blacksmithing.jpg',
  'Leatherworking': 'https://wow.zamimg.com/images/wow/icons/large/trade_leatherworking.jpg',
  'Tailoring': 'https://wow.zamimg.com/images/wow/icons/large/trade_tailoring.jpg',
  'Engineering': 'https://wow.zamimg.com/images/wow/icons/large/trade_engineering.jpg',
  'Alchemy': 'https://wow.zamimg.com/images/wow/icons/large/trade_alchemy.jpg',
  'Jewelcrafting': 'https://wow.zamimg.com/images/wow/icons/large/inv_misc_gem_01.jpg',
  'Enchanting': 'https://wow.zamimg.com/images/wow/icons/large/trade_engraving.jpg',
  'Inscription': 'https://wow.zamimg.com/images/wow/icons/large/inv_inscription_tradeskill01.jpg'
};

export const gearIcons = {
  'Helm': 'https://wow.zamimg.com/images/wow/icons/large/inv_helmet_06.jpg',
  'Shoulders': 'https://wow.zamimg.com/images/wow/icons/large/inv_shoulder_02.jpg',
  'Back': 'https://wow.zamimg.com/images/wow/icons/large/inv_misc_cape_11.jpg',
  'Chest': 'https://wow.zamimg.com/images/wow/icons/large/inv_chest_cloth_17.jpg',
  'Wrists': 'https://wow.zamimg.com/images/wow/icons/large/inv_bracer_17.jpg',
  'Hands': 'https://wow.zamimg.com/images/wow/icons/large/inv_gauntlets_17.jpg',
  'Waist': 'https://wow.zamimg.com/images/wow/icons/large/inv_belt_15.jpg',
  'Legs': 'https://wow.zamimg.com/images/wow/icons/large/inv_pants_cloth_21.jpg',
  'Boots': 'https://wow.zamimg.com/images/wow/icons/large/inv_boots_05.jpg',
  'Main Hand': 'https://wow.zamimg.com/images/wow/icons/medium/inv_sword_24.jpg',
  'Off-hand': 'https://static.wikia.nocookie.net/wowpedia/images/5/5a/Inv_offhand_blood_02.png',
  'Ring': 'https://wow.zamimg.com/images/wow/icons/medium/inv_jewelry_ring_81.jpg',
  'Red Gem': 'https://wow.zamimg.com/images/wow/icons/large/inv_misc_gem_x4_rare_cut_red.jpg',
  'Blue Gem': 'https://wow.zamimg.com/images/wow/icons/large/inv_misc_gem_x4_rare_cut_blue.jpg',
  'Yellow Gem': 'https://wow.zamimg.com/images/wow/icons/large/inv_misc_gem_x4_rare_cut_yellow.jpg',
  'Green Gem': 'https://wow.zamimg.com/images/wow/icons/large/inv_misc_gem_x4_rare_cut_green.jpg',
  'Purple Gem': 'https://wow.zamimg.com/images/wow/icons/large/inv_misc_gem_x4_rare_cut_purple.jpg',
  'Orange Gem': 'https://wow.zamimg.com/images/wow/icons/large/inv_misc_gem_x4_rare_cut_orange.jpg',
  'Prismatic Gem': 'https://wow.zamimg.com/images/wow/icons/medium/inv_jewelcrafting_cut-standart-gem-hybrid_color1_3.jpg',
  'Meta Gem': 'https://wow.zamimg.com/images/wow/icons/medium/inv_misc_gem_x4_metagem_cut.jpg',
  'Flask': 'https://wow.zamimg.com/images/wow/icons/medium/inv_flask_red.jpg',
  'Potion/Elixir': 'https://wow.zamimg.com/images/wow/icons/large/inv_potion_107.jpg',
  'Glyph': 'https://wow.zamimg.com/images/wow/icons/medium/inv_glyph_minorhunter.jpg',
  'Transmutation': 'https://static.wikia.nocookie.net/wowpedia/images/7/7e/Spell_nature_abolishmagic.png',
  'Scroll': 'https://wow.zamimg.com/images/wow/icons/medium/inv_scroll_07.jpg',
  'Shirt':'https://wow.zamimg.com/images/wow/icons/medium/inv_shirt_white_01.jpg',
  'Ink' :'https://wow.zamimg.com/images/wow/icons/medium/inv_inscription_inkblack02.jpg',
  'Misc' :'https://wow.zamimg.com/images/wow/icons/medium/inv_misc_bag_10_black.jpg',
  'Inscription': 'https://wow.zamimg.com/images/wow/icons/large/inv_inscription_tradeskill01.jpg',
  'Bag': 'https://wow.zamimg.com/images/wow/icons/medium/inv_misc_bag_23_netherweave.jpg',
};
