export const invTypeMap = {
  INVTYPE_HEAD: 'Helm',
  INVTYPE_SHOULDER: 'Shoulders',
  INVTYPE_CLOAK: 'Back',
  INVTYPE_CHEST: 'Chest',
  INVTYPE_ROBE: 'Chest',
  INVTYPE_WRIST: 'Wrists',
  INVTYPE_HAND: 'Hands',
  INVTYPE_WAIST: 'Waist',
  INVTYPE_LEGS: 'Legs',
  INVTYPE_FEET: 'Boots',
  INVTYPE_2HWEAPON: 'Main Hand',
  INVTYPE_WEAPON: 'Main Hand',
  INVTYPE_WEAPONMAINHAND: 'Main Hand',
  INVTYPE_WEAPONOFFHAND: 'Off-hand',
  INVTYPE_HOLDABLE: 'Off-hand',
  INVTYPE_SHIELD: 'Off-hand',
  INVTYPE_FINGER: 'Ring',
  INVTYPE_NECK: 'Neck',
  INVTYPE_TRINKET: 'Trinket',
  INVTYPE_RANGEDRIGHT: 'Wand',
  INVTYPE_THROWN: 'Ranged',
  INVTYPE_NON_EQUIP_IGNORE: 'Misc',
  INVTYPE_BAG: 'Bag',
  INVTYPE_BODY: 'Shirt',
};
